//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education
    {
        public int EducationId { get; set; }
        public int EmployeeId { get; set; }
        public int CertificateId { get; set; }
        public int InstituteId { get; set; }
        public string GroupName { get; set; }
        public System.DateTime Year { get; set; }
        public int ResultId { get; set; }
    
        public virtual Certificate Certificate { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Institute Institute { get; set; }
        public virtual Result Result { get; set; }
    }
}
