//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeInfo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Institute
    {
        public Institute()
        {
            this.Educations = new HashSet<Education>();
        }
    
        public int InstituteId { get; set; }
        public string InstituteName { get; set; }
    
        public virtual ICollection<Education> Educations { get; set; }
    }
}
